DROP TABLE IF EXISTS organizations CASCADE;
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS permissions CASCADE;
DROP TABLE IF EXISTS website_passwords CASCADE;
DROP TABLE IF EXISTS website_url_details CASCADE;

CREATE TABLE organizations (
  id SERIAL PRIMARY KEY NOT NULL,
  name VARCHAR(255)
);

CREATE TABLE permissions (
  id SERIAL PRIMARY KEY NOT NULL,
  role VARCHAR(25) NOT NULL
);

CREATE TABLE users (
  id SERIAL PRIMARY KEY NOT NULL,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL,
  organization_id INTEGER NOT NULL REFERENCES organizations(id)  ON DELETE CASCADE,
  permission_id INTEGER DEFAULT 2 NOT NULL REFERENCES permissions(id)  ON DELETE CASCADE
);

CREATE TABLE website_url_details (
  id SERIAL PRIMARY KEY NOT NULL,
  url VARCHAR(255) NOT NULL,
  website_type VARCHAR(52) NOT NULL
);

CREATE TABLE website_passwords (
  id SERIAL PRIMARY KEY NOT NULL,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  website_url_id INTEGER NOT NULL REFERENCES website_url_details(id) ON DELETE CASCADE,
  website_username VARCHAR(255) NOT NULL,
  generated_password VARCHAR(255) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT NOW()
);
