INSERT INTO organizations (id, name) VALUES (1, 'Hodkiewicz, Crist and Hackett');
INSERT INTO organizations (id, name) VALUES (2, 'Blick, MacGyver and Vandervort');
INSERT INTO organizations (id, name) VALUES (3, 'Bednar and Sons');
INSERT INTO organizations (id, name) VALUES (4, 'Grady Inc');
INSERT INTO organizations (id, name) VALUES (5, 'Gulgowski-Langosh');
INSERT INTO organizations (id, name) VALUES (6, 'Daniel LLC');
INSERT INTO organizations (id, name) VALUES (7, 'Waelchi, Becker and Nicolas');
INSERT INTO organizations (id, name) VALUES (8, 'O''Keefe-Morissette');
INSERT INTO organizations (id, name) VALUES (9, 'Hessel-Labadie');
INSERT INTO organizations (id, name) VALUES (10, 'Wyman-Stiedemann');
INSERT INTO organizations (id, name) VALUES (11, 'Kunde Group');
INSERT INTO organizations (id, name) VALUES (12, 'McGlynn, Daugherty and Emmerich');
INSERT INTO organizations (id, name) VALUES (13, 'Emard-Gusikowski');
INSERT INTO organizations (id, name) VALUES (14, 'Rutherford-Hammes');
INSERT INTO organizations (id, name) VALUES (15, 'Hayes, Bruen and Schimmel');
INSERT INTO organizations (id, name) VALUES (16, 'Durgan-Waters');
INSERT INTO organizations (id, name) VALUES (17, 'Rolfson-Kuhic');
INSERT INTO organizations (id, name) VALUES (18, 'Reichel, Green and O''Hara');
INSERT INTO organizations (id, name) VALUES (19, 'Heller LLC');
INSERT INTO organizations (id, name) VALUES (20, 'Willms, Schmeler and Bradtke');
